services:
  tiendaservicios.api.autor:
    image: tiendaservicioautor-app:1.0
    ports:
        - "8080:80"
    build:
      context: .
      dockerfile: TiendaServicios.Api.Autor/Dockerfile
  tiendaservicios.api.libro:
    image: tiendaserviciolibro-app:1.0
    ports:
        - "8081:80" 
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libro/Dockerfile

  tiendaservicios.api.carritocompra:
    image: tiendaserviciocarritocompra-app:1.0
    ports:
        - "8082:80"
    build:
      context: .
      dockerfile: TiendaServicios.Api.CarritoCompra/Dockerfile

  tiendaservicios.api.gateway:
    image: tiendaserviciogateway-app:1.0
    depends_on:
      - tiendaservicios.api.libro
    ports:
        - "8083:80"
    build:
      context: .
      dockerfile: TiendaServicios.Api.Gateway/Dockerfile

networks:
  default:
        external:
            name: microservicenet





